<%@ Page Title="Home Page" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="EmployeeDirectory._Default" %>

<asp:Content runat="server" ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h2>Search for Employees here</h2>
            </hgroup>
            <p>
                here are simple instructions for use
            </p>
        </div>
    </section>
</asp:Content>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <h3>This is where we will store the controls.</h3>
    <ol class="round">
        <li class="one">
            <h5>Here are some search controls.</h5>
            <table>
                <tr>
                    <td>
                        <asp:Label runat="server" ID="Label1">First Name</asp:Label><br />
                        <asp:TextBox runat="server" ID="txtFirst" ></asp:TextBox>
                    </td>
                    <td>
                        <asp:Label runat="server" ID="Label2">Last Name</asp:Label><br />
                        <asp:TextBox runat="server" ID="txtLast"></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td>
                        <asp:Label runat="server" ID="Label3">Employee ID</asp:Label><br />
                        <asp:TextBox runat="server" ID="txtEmpId" TextMode="Number" ></asp:TextBox>
                    </td>
                    <td>
                        <asp:Label runat="server" ID="Label4">Email</asp:Label><br />
                        <asp:TextBox runat="server" ID="txtEmail" ></asp:TextBox>
                    </td>
                </tr>
                <tr>
                    <td colspan="2">
                        <asp:Label runat="server" ID="Label5">Location:</asp:Label>
                        <asp:DropDownList runat="server" ID="ddlLocation"></asp:DropDownList>
                        <asp:Label runat="server" ID="Label6">Role:</asp:Label>
                        <asp:DropDownList runat="server" ID="ddlRole"></asp:DropDownList>
                        <asp:Label runat="server" ID="Label7">Status:</asp:Label>
                        <asp:DropDownList runat="server" ID="ddlStatus"></asp:DropDownList>
                    </td>
                </tr>
            </table>
            <asp:Button ID="btnSearch" runat="server" OnClick="btnSearch_Click" Text="Search" />
        </li>
        <li class="two">
            <h5>Results</h5>
            
            <asp:UpdatePanel ID="pnlGridPanel" runat="server">
                <ContentTemplate>
                    <asp:GridView ID="gvEmployee" runat="server" AutoGenerateColumns="true" AutoGenerateEditButton="true" 
                        AutoGenerateDeleteButton="false" AutoGenerateSelectButton="false" AllowPaging="true"
                        OnPageIndexChanging ="indexChanged" OnRowCommand="rowCommand" OnRowEditing="rowEdit" 
                        OnRowCancelingEdit="rowEditCancel" OnRowUpdating="rowUpdating" OnRowDataBound="gridBinding"
                         RowStyle-Wrap="false">
                        <Columns>                             
                        </Columns>
                    </asp:GridView>
                </ContentTemplate>
            </asp:UpdatePanel>
        </li>
    </ol>
</asp:Content>
